---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 78778.
--- DateTime: 2022/3/13 17:52
---

require 'Class'

Bird = Class()

Bird.Ctor = function(self, color, shitOnPeople)
    print('a new bird born')
    self.color = color
    self.shitOnPeople = shitOnPeople
end

Bird.Fly = function()
    print('i can fly ~')
end

Bird.SayHello = function(self)
    print(string.format("I'm a %s color bird, i %s like shit on people", self.color, self.shitOnPeople and 'like' or 'don\'t like'))
end
