---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 78778.
--- DateTime: 2022/3/6 15:49
---


Class = function(base)
    local proto = {}
    setmetatable(proto, {__index = base})
    proto.base = base
    proto.__classtype = proto
    proto.New = function(...)
        local obj = setmetatable({}, {__index = proto})
        -- 递归的执行父类构造函数
        local create
        create = function(c, ...)
            if c.base then
                create(c.base,...)
            end
            if c.Ctor then
                c.Ctor(obj,...)
            end
        end

        create(proto, ...)
        return obj
    end

    return proto
end