---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 78778.
--- DateTime: 2022/3/13 17:58
---


require 'Bird'
require 'Swallow'


local bird = Bird.New('white', true)
local swallow1 = Swallow.New('black', true)
local swallow2 = Swallow.New('yellow', false)


bird:Fly()
swallow1:Fly()
swallow2:SayHello()