---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 78778.
--- DateTime: 2022/3/13 17:55
---

require 'Class'
require 'Bird'

Swallow = Class(Bird)

Swallow.Ctor = function(self, color, shitOnPeople)
    print('a new swallow born')
end


Swallow.Sing = function()
    print('i like sing~~')
end